//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LevelUpPCStore
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product_Cart
    {
        public int Id { get; set; }
        public int Id_Cart { get; set; }
        public int Id_Product { get; set; }
        public int Quantity { get; set; }
    
        public virtual Cart Cart { get; set; }
        public virtual Product Product { get; set; }
    }
}
